project:
  type: website
  render:
    - index.qmd
website:
  title: "Methane Detection"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: README.txt
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true
execute:
  echo: true
  warning: false
  message: false
  freeze: auto
  
editor: visual