project:
  type: website
  render:
    - index.qmd
website:
  title: "Methane Detection"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: fit_models.R
        text: Models
      - href: data/methane_df.zip
        text: Data

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true
execute:
  echo: true
  warning: false
  message: false
  freeze: auto
  
editor: visual